### ISSUE TITLE
scanmem: assert triggered with `0> <operator> <number>`

### ISSUE THREAD

**Issue by mdziczkowski** [scanmem/scanmem#217] opened 2016-09-28 18:44 UTC
hello. After installing and launching scanmem, I tryed to find the first value. Bellow are all steps I did (I had truncated the less important informations):

```
$ scanmem
scanmem version 0.13

Enter the pid of the process to search using the "pid" command.

0> pid 12810
info: maps file located at /proc/12810/maps opened.
info: 107 suitable regions found.
0> = 126
info: 01/107 searching 0x7f41b6500000 - 0x7f41ba200000.scanmem: scanroutines.c:82: scan_routine_INTEGER8_NOTCHANGED: Assertion `old_value' failed.
error: 
Killed by signal 6.
```

**Comment by 12345ieee** [comment] 2016-09-28 19:02
Confirmed in 0.16~pre.

The bug is triggered, when there are no matches, by 

    0> <operator> <number>

where <operator> is one of the "compare with last scan" operators.
Pretty sure it's a parser error.

For @mdziczkowski , your command is an invalid one, to look for locations with 126 in you simply need

    0> 126

**Comment by mdziczkowski** [comment] 2016-10-01 09:23
@12345ieee thanks. I'm new to scanmem and the man is not very helpfull for those who just start

**Comment by 12345ieee** [comment] 2016-10-02 12:18
The manual was greatly improved in 0.16, which will soon (TM) release in your favourite distribution.

I'm renaming this issue to reflect the `<operator> <number>` bug.

**Comment by mdziczkowski** [comment] 2016-10-03 22:25
@12345ieee soon means when? it's a very relative term of time ;)

**Comment by 12345ieee** [comment] 2016-10-04 14:28
The 'soon (TM)' was humor, there is not a release date set, yet.

#219 should have the fix for this.

I also made `= N` supported syntax, because, well, it makes sense.

**Comment by mdziczkowski** [comment] 2016-10-04 17:06
@12345ieee do you think this will be enough to make it work correctly? theoretically the code looks like it could do the trick, but it would be a good idea if there is no other thing with could make it don't work

**Comment by 12345ieee** [comment] 2016-10-04 19:22
@mdziczkowski , the code looked quite simple, I'm confident it'll work (and works for all the inputs I tried). You can build from the PR and try it yourself.

@sriemer will have the last word, once he gets some time.

**Closed** 2016-12-16 22:07 UTC
Labels: bug
