### ISSUE TITLE
GC Bug: Freeze after scan for string

### ISSUE THREAD

**Issue by DHLF** [scanmem/scanmem#358] opened 2019-10-27 16:33 UTC
Linux Mint 19.3/ GC 0.17

I wanted to rename some equipment in Fallout4.
Ran a search for **Champion,**(including comma to get less wrong results), but GC freezed after search ended.
Also a new icon showed up in those bar(left of notification/time/etc) about "Remove superuser clearance?". Bad translation, sorry so: It sounded like hitting those button would remove all previous sudos allowances(like for GC?).
Killed the frozen GC, ran GC again and selected some other process and searched there(for a different string). Worked fine.

Searched(attached to fallout4) again for just **Champion** worked(but too many hits).
Searched for **Champion,**(with comma!) and GC freezed again.

TLTR: Adding a sole comma as last sign of a string keeps GC freezing after search ended.

**Comment by sriemer** [comment] 2019-10-27 16:45
String search has been reworked since 0.17. Please try again with latest Git master commit 64aba07b4022c69fd81c1b833628d36723fb2185. If latest code is not affected, then it is up to the distro picking up the proper fixes from upstream.
Please try to reproduce against FOSS games as well so that we have a chance to reproduce and debug ourselves. TIA

**Comment by DHLF** [comment] 2019-10-27 19:43
TLTR:
Confirmed this error still exists using 0.18~dev:
 we currently have 7 matches.
Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 1144, in data_worker
    new_value = self.read_value(addr, TYPENAMES_S2G[scanmem_type.split(' ', 1)[0]], cur_value)
KeyError: ''

This happens also in firefox, .. if a string search got as last sign a comma.

The search always completes with a different number of hits found. THEN it freezes.

As far as I understand this issue.. the comma seems to be interpreted as an unknown "separator" so instead of searching for the sign itself GC gets confused.



Ouch.. 
I was using the current 0.17 from the linux mint repository.
Fetched the **master branch** https://github.com/scanmem/scanmem 64aba07 (zip file, extracted the folder, made file autogen.sh executable) and during build time there were some errors shown, but I think they are not really important:

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -std=gnu99 -Wall -g -O2 -MT show_message.lo -MD -MP -MF .deps/show_message.Tpo -c show_message.c  -fPIC -DPIC -o .libs/show_message.o
show_message.c: In function ‘get_pager’:
show_message.c:119:5: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
     write(pgpipe[1], "", 1);
     ^~~~~~~~~~~~~~~~~~~~~~~
show_message.c:138:9: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
         read(pgpipe[0], &nullbuf, 1);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
show_message.c:139:9: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
         write(pgpipe[1], "1", 2);
         ^~~~~~~~~~~~~~~~~~~~~~~~
Made gameconqueror in /scanman-master/gui executable and ran the script:
(links to  DATADIR=/usr/share/gameconqueror but there is still the old version!)

These are two places where gameconqueror is found on my system:
**/usr/share/gameconqueror** (folder) contains files dated 26.01.2018
**~/Download/scanmem-master/gui/gameconqueror** dated 27.10.2019

[edit] After some struggeling i found out that due to unknown error during installation the new files were NOT copied to the target location at **/usr/share/gameconqueror**.

Anyway I ran it(the old 0.17) and  searched for a string in firefox(ending with comma):
The search always completes with a different number of hits found. THEN it freezes.

As far as I understand this issue.. the comma seems to be interpreted as an unknown "separator" so instead of searching for the sign itself GC gets confused. 

**Traceback** (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 1133, in data_worker
    new_value = self.read_value(addr, TYPENAMES_S2G[scanmem_type.split(' ', 1)[0]], cur_value)
KeyError: ''

At this point I saw the log reading /usr/share/GameConqueror so I did something wrong above.

Running the  **new** GC directly using _python gameconqueror.py_ 

$ python GameConqueror.py 
Traceback (most recent call last):
  File "GameConqueror.py", line 1206, in <module>
    gc_instance = GameConqueror()
  File "GameConqueror.py", line 335, in __init__
    self.backend = GameConquerorBackend(os.path.join(LIBDIR, 'libscanmem.so.1'))
  File "/home/hejn/Downloads/scanmem-master/gui/backend.py", line 42, in __init__
    self.lib = ctypes.CDLL(libpath)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libscanmem.so.1: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden

It DOES exist under:
/usr/lib/scanmem/libscanmem.so.1 (112.664bytes again dated early 2018)
~/Downloads/scanmem-master/.libs/libscanmem.so.1 (663.216 the *new* version)

Okay, manually copied the NEW 2019 files:
**@libscanmem.so.1** and **libscanmem.so.1.0.0** to **/usr/lib/** 
NOW I can run using python the new version 0.18~dev

New try. Scanned for something, in an instand the scan was complete. But..:

info: maps file located at /proc/7489/maps opened.
info: 356 suitable regions found.
error: failed to attach to 7489, Vorgang nicht zulässig
error: failed to search target address space.

Running python directly without the possibility to use SUDO.. seems pointless.

Next try.. copied all corresponding files from /master/gui/ to /usr/share/gameconqueror.

**It was a BAD idea to copy the files. DONT try this without timemachine etc.!**. I broke gc completely. It runs but after the confirmation of sudo stuff it exits. Meh. 
Removing GC using apt remove and reinstalling did not fix it. 
Removed also scanmem and the manually copied files /usr/lib/libscanmem.so.1 / 1.0.0
run the installation scripts using sudo.
also the command line 
./configure --prefix=/usr --enable-gui && make sudo make install 
seems to be broken in two parts.. -.- 
the second part was **make install**. Or was it intended?? Ouch! 
Ran manually **sudo make install** and it seems okay now.

The *new* 0.18~dev behaves slightly different as the 0.17 as I added something like --geometry (various values) to try to fix a larger window at the start.
Due to this command the *new* version exits after the security check. After I removed the running parameter in the menu it runs without problems. 
Running GC using console command gameconqueror works fine but leaves a console window open.

**Comment by 12345ieee** [comment] 2019-10-27 20:24
Thanks for reporting this freeze.

This is a result of an error in parsing the `list` output of libscanmem when a string as commas in it.

I'll fix it shortly.

**Comment by 12345ieee** [comment] 2019-10-27 21:15
Pushed the fix to master, @DHLF please test at your convenience.

**Comment by DHLF** [comment] 2019-10-28 19:05
### TLTR:
The previous version I tried (first time use of a 0.18~dev) was much faster while comparing numbers. Great!

I am sorry,but this seems to be a broken version now (21ec767).
Neither scans for numbers nor string search works anymore.

I will roll back to the 64aba07 and try if its another error on my side or.. 

### Sample output for int32 search:
info: we currently have 2095 matches.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/gameconqueror/GameConqueror.py", line 1046, in scan_thread_func
    self.update_scan_result()
  File "/usr/share/gameconqueror/Game Conqueror.py", line 1070, in update_scan_result
    (mid_str, addr_str, off_str, rt, val, t) = line_regex.match(line).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
GC hangs now.

### Sample output for string search(like YabbaDabbbaDoo):
info: maps file located at /proc/8676/maps opened.
info: 358 suitable regions found.
..........info: we currently have 0 matches.
GC works fine.. without a match.

### Sample output string search with some matching strings:
info: maps file located at /proc/8676/maps opened.
info: 358 suitable regions found.
......
info: we currently have 319 matches.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/gameconqueror/GameConqueror.py", line 1046, in scan_thread_func
    self.update_scan_result()
  File "/usr/share/gameconqueror/GameConqueror.py", line 1070, in update_scan_result
    (mid_str, addr_str, off_str, rt, val, t) = line_regex.match(line).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
GC hangs.

### Funny installation trouble(more or less)..
Okay, it seems as if some of my installation trouble was made by stupid me..
Instead of following the installation instruction properly like:

First fetching the current version (zip/git), extract the folder from the archive,
then run within the folder(perhaps mods  +x it if necessary):
**./autogen.sh**

Then building WITH gui:
**./configure --prefix=/usr --enable-gui && make**

At last:
**sudo make install**

I accidently marked the last both commands and pasted them TOGETHER
which reads somehow different in the console:
**./configure --prefix=/usr --enable-gui && make sudo make install**
-.-

(Sorry, the last time I used make install etc. was more than fifteen years ago.. windooze and linux mint did fine enough for keeping me away from touching the system myself this way.)

Even following the installation hint properly, some files still got different sizes(comparing the **/usr/share/gameconqueror/** and the **/master/gui/** folders).
Removed the **/usr/share/gameconqueror** folder manually and did installation again.

(its hard to see which version is installed if both are named the same "0.18~dev").

**Comment by 12345ieee** [comment] 2019-10-28 19:20
Github decided to close this automatically, because I've just pushed the fix.
I'll reopen it, hopefully this one will work.

**Comment by DHLF** [comment] 2019-10-28 19:29
69a63a8 just tested. 
String search now don't freeze GC if a string ends with a comma.
What an invisible single space can do ;)

**Comment by 12345ieee** [comment] 2019-10-28 20:02
String and bytearray searches against old values used to be obscenely slow, now they're nearly as fast as numbers. The magic was done mostly in #267 .

Closing this, thanks for the test.

**Closed by 12345ieee** 2019-10-28 20:02 UTC
Labels: GUI, bug
