### ISSUE TITLE
Memory locations change after game reload

### ISSUE THREAD

**Issue by Motherboard** [scanmem/scanmem#316] opened 2018-05-24 11:52 UTC
After locating the memory address belonging to a certain variable, and then reloading from a previous save (tried it with Witcher 2), the memory location no longer points to that variable.

Cheat Engine seems to be resistant to this kind of change, possibly by looking at the memory structure around that location, detecting a change in that region, and re-locating that structure again instead of using an absolute memory address.

**Comment by 12345ieee** [comment] 2018-05-24 11:58
This is a duplicate of #301 , which has an in-depth technical discussion.

scanmem/GC can't do this, you need something with the capabilities of a debugger.
So `gdb`, `ugtrain` and (sometime in the future) `PINCE`.

**Closed by 12345ieee** 2018-05-24 11:58 UTC
