### ISSUE TITLE
gameconqueror generates many deprecated operations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [scanmem/scanmem#75] opened 2015-03-14 06:57 UTC
```
/usr/share/gameconqueror/GameConqueror.py:1009: PyGIDeprecationWarning: Since 
version 3.11, calling threads_init is no longer needed. See: 
https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
/usr/share/gameconqueror/hexview.py:512: PyGTKDeprecationWarning: Using 
positional arguments with the GObject constructor has been deprecated. Please 
specify keyword(s) for "homogeneous, spacing" or use a class specific 
constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  super(HexView, self).__init__(False, 4)
/usr/share/gameconqueror/GameConqueror.py:149: PyGTKDeprecationWarning: The 
keyword(s) "page_incr, step_incr" have been deprecated in favor of 
"page_increment, step_increment" respectively. See: 
https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.search_scope_scale_adjustment = Gtk.Adjustment(lower=0, upper=2, step_incr=1, page_incr=1, page_size=0)
/usr/share/gameconqueror/misc.py:154: PyGTKDeprecationWarning: Using positional 
arguments with the GObject constructor has been deprecated. Please specify 
keyword(s) for "label" or use a class specific constructor. See: 
https://wiki.gnome.org/PyGObject/InitializerDeprecations
  item = Gtk.MenuItem(name)
/usr/share/gameconqueror/GameConqueror.py:299: PyGIDeprecationWarning: 
timeout_add is deprecated; use GLib.timeout_add instead
  GObject.timeout_add(DATA_WORKER_INTERVAL, self.data_worker)
[brain@X1Carbon scanmem]$ gameconqueror 
/usr/share/gameconqueror/GameConqueror.py:1009: PyGIDeprecationWarning: Since 
version 3.11, calling threads_init is no longer needed. See: 
https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
/usr/share/gameconqueror/hexview.py:512: PyGTKDeprecationWarning: Using 
positional arguments with the GObject constructor has been deprecated. Please 
specify keyword(s) for "homogeneous, spacing" or use a class specific 
constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  super(HexView, self).__init__(False, 4)
/usr/share/gameconqueror/GameConqueror.py:149: PyGTKDeprecationWarning: The 
keyword(s) "page_incr, step_incr" have been deprecated in favor of 
"page_increment, step_increment" respectively. See: 
https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.search_scope_scale_adjustment = Gtk.Adjustment(lower=0, upper=2, step_incr=1, page_incr=1, page_size=0)
/usr/share/gameconqueror/misc.py:154: PyGTKDeprecationWarning: Using positional 
arguments with the GObject constructor has been deprecated. Please specify 
keyword(s) for "label" or use a class specific constructor. See: 
https://wiki.gnome.org/PyGObject/InitializerDeprecations
  item = Gtk.MenuItem(name)
/usr/share/gameconqueror/GameConqueror.py:299: PyGIDeprecationWarning: 
timeout_add is deprecated; use GLib.timeout_add instead
  GObject.timeout_add(DATA_WORKER_INTERVAL, self.data_worker)
/usr/share/gameconqueror/GameConqueror.py:646: PyGTKDeprecationWarning: Using 
positional arguments with the GObject constructor has been deprecated. Please 
specify keyword(s) for "parent, flags, message_type, buttons, message_format" 
or use a class specific constructor. See: 
https://wiki.gnome.org/PyGObject/InitializerDeprecations
  ,msg)
/usr/share/gameconqueror/GameConqueror.py:646: PyGTKDeprecationWarning: The 
keyword(s) "message_format" have been deprecated in favor of "text" 
respectively. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  ,msg)
/usr/share/gameconqueror/GameConqueror.py:646: PyGTKDeprecationWarning: The 
"flags" argument for dialog construction is deprecated. Please use initializer 
keywords: modal=True and/or destroy_with_parent=True. See: 
https://wiki.gnome.org/PyGObject/InitializerDeprecations
  ,msg)
/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py:532: 
PyGTKDeprecationWarning: The keyword(s) "parent" have been deprecated in favor 
of "transient_for" respectively. See: 
https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self._init(*args, **new_kwargs)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
/usr/share/gameconqueror/GameConqueror.py:350: PyGTKDeprecationWarning: Using 
positional arguments with the GObject constructor has been deprecated. Please 
specify keyword(s) for "title, parent, action, buttons" or use a class specific 
constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  Gtk.STOCK_OPEN, Gtk.ResponseType.OK))
/usr/share/gameconqueror/GameConqueror.py:350: PyGTKDeprecationWarning: The 
"buttons" argument must be a Gtk.ButtonsType enum value. Please use the 
"add_buttons" method for adding buttons. See: 
https://wiki.gnome.org/PyGObject/InitializerDeprecations
  Gtk.STOCK_OPEN, Gtk.ResponseType.OK))

```

Original issue reported on code.google.com by `i.gnaten...@gmail.com` on 16 Jun 2014 at 5:26

**Comment by sriemer** [comment] 2015-03-29 11:15
I've tested this against Python 2.7 and 3.4 with python-gtk2 2.24 on Ubuntu 14.04 amd64 and I can't reproduce this. Seems like this can only be reproduced by using python-gtk3.

**Comment by sriemer** [comment] 2015-03-29 14:26
Closing for now as it can't be reproduced.

**Closed by sriemer** 2015-03-29 14:26 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
