### ISSUE TITLE
Killed by signal 11

### ISSUE THREAD

**Issue by MichaelElianKevin** [scanmem/scanmem#335] opened 2019-05-23 00:57 UTC
When i did search i got killled by signal 11.
hot to fix that?

**Comment by sriemer** [comment] 2019-05-23 06:33
Duplicate of #307. Out of memory. Try to look for a value which is less common than e.g. 0 or free up more RAM.

**Closed by sriemer** 2019-05-23 06:33 UTC

**Comment by MichaelElianKevin** [comment] 2019-05-23 06:51
how to fix that, i have much free space RAM.
