### ISSUE TITLE
In the event of zero results; code search; debugger integration

### ISSUE THREAD

**Issue by 3vi1** [scanmem/scanmem#158] opened 2016-04-11 19:39 UTC
I was just tracking down a memory location, and accidentally searched for my "+ 1" twice (without doing the game action that would have actually incremented the memory.  This, of course, took my list down from 200 locations to zero.

If the search would result in zero memory locations, how about leaving the previous locations loaded and pop up a dialog saying there were zero viable locations?  This could be optional, but seems like a more useful default behavior.

I guess an alternate option would be to maintain an 'undo' list.

**Comment by sriemer** [comment] 2016-04-11 20:58
How should you know if your old matches are still valid?

How important is that for you?

Is it really worth changing the main concepts/design of scanmem and to maintain a backup of the matches in memory?

This is rather human error.

I'm tending to reject this to be honest.

**Comment by rumbleh** [comment] 2016-04-11 21:04
Hi! I can search for arm opcodes instead memory values?

Example: I have found the instruction:

sub r0, #1

then i want to change to
add r0, #1

Instead patching and loosing the signature of original apk,  I would like
only in memory.

Can I do with this tool?

thanks!


*____________*
E se o meu povo, que se chama pelo meu nome, se humilhar, e orar, e buscar
a minha face e se converter dos seus maus caminhos, então eu ouvirei dos
céus, e perdoarei os seus pecados, e sararei a sua terra.
II Crônicas 7:14

2016-04-11 17:58 GMT-03:00 Sebastian Parschauer <notifications@github.com>:

**Comment by sriemer** [comment] 2016-04-11 21:28
@rumbleh That's not possible currently.
scanmem only searches writable regions (.data and .bss) but not read-only ones (.rodata or .text).
I usually set a watch point with gdb and then I use the gdb 'set' command for that.
It is planned to implement a debugger code replacement feature into [ugtrain](https://github.com/ugtrain/ugtrain).
I would like that this is implemented into scanmem.

**Comment by rumbleh** [comment] 2016-04-12 03:09
Thank you for your response. When I set a breakpoint on GDB using address
found in IDA, it says that modules are not loaded.

I'm using a gdb version posted on VisualGDB site, then ran the gdbserver
and connect through SSH.

Anyway, this feature would be nice. :) bye


*____________*
E se o meu povo, que se chama pelo meu nome, se humilhar, e orar, e buscar
a minha face e se converter dos seus maus caminhos, então eu ouvirei dos
céus, e perdoarei os seus pecados, e sararei a sua terra.
II Crônicas 7:14

2016-04-11 18:28 GMT-03:00 Sebastian Parschauer <notifications@github.com>:

**Comment by sriemer** [comment] 2016-04-12 07:29
Looks like you're not familiar enough with gdb. It doesn't require any debugging symbols.
````
(gdb) break *40057e
Breakpoint 1 at 0x40057e
(gdb) run
````
Mixing Windows and Linux methods might be a problem here.

Another example with the lives in the HeroAircraft object in Chromium B.S.U.:

scanmem after locating the lives on the heap:
````
1> list
[ 0] 7f2a5f9cdc1c, 27 +       460c1c,  heap, 2, [I64 I32 I16 I8 ]
1> set 9
info: setting *0x7f2a5f9cdc1c to 0x9...
1> exit
````

gdb to get the code reducing the lives:
````
(gdb) watch *0x7f2a5f9cdc1c
Hardware watchpoint 1: *0x7f2a5f9cdc1c
(gdb) continue
Continuing.
Hardware watchpoint 1: *0x7f2a5f9cdc1c

Old value = 0x9
New value = 0x8
0x00007f2a5f2db619 in ?? ()

(gdb) disassemble 0x00007f2a5f2db609,+20
Dump of assembler code from 0x7f2a5f2db609 to 0x7f2a5f2db629:
   0x00007f2a5f2db609:	cmp    ebp,0x3
   0x00007f2a5f2db60c:	jne    0x7f2a5f2db526
   0x00007f2a5f2db612:	sub    DWORD PTR [rbx+0xbc],0x1
=> 0x00007f2a5f2db619:	mov    DWORD PTR [rbx+0xec],0x0
   0x00007f2a5f2db623:	mov    rdi,rbx
   0x00007f2a5f2db626:	mov    DWORD PTR [rbx+0xf0],0x0
````

You can use the `set` command described [here](http://stackoverflow.com/questions/6473908/can-gdb-change-the-assembly-code-of-a-running-program) afterwards.

Btw.: This is a position-independent executable (PIE) here. So code addresses are also randomized by ASLR at every game start.

**Comment by sriemer** [comment] 2016-04-12 09:46
@rumbleh: Do you know that scanmem has an automatic PIC and PIE load address gatherer to bypass ASLR in static memory?

You can see the load address in the `lregions` command. The region type is also based on this. It is detected which memory regions belong to the same ELF executable/library. In the matches list there is a match offset which is `match address - load address`.

I've implemented this to make static memory values static again with the counter part implemented in [ugtrain](https://github.com/ugtrain/ugtrain). It is the only game trainer on Linux with PIE support and therefore also static memory locking/freezing within .data or .bss of a PIE.

Ugtrain doesn't change any code currently. But with preloading and API hooking it has really powerful dynamic memory locking/freezing support with automatic adaptation to new game versions/compilers/distributions. If a memory value can be found with scanmem, then ugtrain can reliably lock/freeze it in every game run in most cases.

**Comment by sriemer** [comment] 2016-04-13 07:22
I've tried the search in .text of the exe by dropping the write check in maps.c. The problem is that code doesn't change. So it is only possible to use the initial search. Then you have to hope that the code pattern is rare.

Chromium B.S.U. example:
`objdump -D` output of the PIE after searching for "/sub.*bc":
````
   1960c:       0f 85 14 ff ff ff       jne    19526 <_ZN13EnemyAircraft17printNumAllocatedEv+0xc0d6>
   19612:       83 ab bc 00 00 00 01    subl   $0x1,0xbc(%rbx)
   19619:       c7 83 ec 00 00 00 00    movl   $0x0,0xec(%rbx)
   19620:       00 00 00 
   19623:       48 89 df                mov    %rbx,%rdi
   19626:       c7 83 f0 00 00 00 00    movl   $0x0,0xf0(%rbx)
````
Part to search for:
````
   19612:       83 ab bc 00 00 00 01    subl   $0x1,0xbc(%rbx)
````
Scanmem bytearray search:
````
0> lregions
0> dregion !22
0> lregions
[22] 7f067ad5b000,  204800 bytes,   exe, 7f067ad5b000, rwx, /usr/games/chromium-bsu
0> option scan_data_type bytearray
0> 83 ab bc 00 00 00 01
2> list
[ 0] 7f067ad74612, 22 +        19612,   exe, 83 ab bc 00 00 00 01, [bytearray]
[ 1] 7f067ad74782, 22 +        19782,   exe, 83 ab bc 00 00 00 01, [bytearray]
2> write bytearray 7f067ad74612 90 90 90 90 90 90 90
2> write bytearray 7f067ad74782 90 90 90 90 90 90 90
````
Nice! That works at least! Lives aren't reduced any more. :smile:

It is also wonderful to see that the match offset (19612) is the address in the objdump output.

**Comment by sriemer** [comment] 2016-04-13 13:39
I would prefer gdb integration into scanmem with a `gdb` command inside scanmem like the `crash` tool does for analyzing Linux kernel crashes.

E.g. setting a watch point would look like this:
````
0> gdb watch *0x7f2a5f9cdc1c
````
The Cheat Engine Dynamic Memory Allocation (DMA) support based on pointer following is also based on setting watch points with a debugger.

**Comment by rumbleh** [comment] 2016-04-13 13:57
Nice! You have nopped those sub calls.

This is what I was trying to do on Android with gdb. Patching in memory.

I have a lot of experience in reverse enginnering Windows Apps, (crks,
keygens, etc), and the software that I use is OllyDBG. So, gdb is
particulary new to me (i have only cheated 2 games using gdb and was on iOS
platform.)

The deal is i didn't found the gdb for Android Lolipop , only gdbserver.

Anyway, I will keep searching on this topic.

Sorry for my grammar error, english is not my native language.


*____________*
E se o meu povo, que se chama pelo meu nome, se humilhar, e orar, e buscar
a minha face e se converter dos seus maus caminhos, então eu ouvirei dos
céus, e perdoarei os seus pecados, e sararei a sua terra.
II Crônicas 7:14

2016-04-13 10:39 GMT-03:00 Sebastian Parschauer <notifications@github.com>:

**Comment by sriemer** [comment] 2016-04-13 14:32
So I was right that you are facing PIE! :smile: I don't really like Android. Android violates POSIX standards, is often insecure and comes from Google. I had a Nokia N9 based on MeeGo 1.2 Harmattan and use a Jolla phone now based on Sailfish OS 2. These are real GNU/Linux systems with glibc instead of bionic stuff.

My ugtrain is also working on these devices and I can do mobile game cheating with dynamic memory support this way. :-) It doesn't only work with FOSS games - believe me! But it requires some more hacks to bypass more security mechanisms on smart phones.

Ugtrain also runs the game, places scanmem as the parent of the game with a chicken-and-egg trick and bypasses the YAMA security module controlling ptrace() access this way. The result is that you can use scanmem and `ptrace()` without root privileges. :smile: I feel safer this way.

**Comment by sriemer** [comment] 2016-04-15 07:02
Questions answered, so closing. I'll think about the debugger integration and open a new issue for this if required.

**Closed by sriemer** 2016-04-15 07:02 UTC
Labels: enhancement, question
