### ISSUE TITLE
gameconqueror don't run on my Fedora

### ISSUE THREAD

**Issue by yodatak** [scanmem/scanmem#292] opened 2017-12-30 23:23 UTC
Hi everyone, i just made a fresh install of gameconqueror and it don't run it ask me my user password for runing and after nothing.
I'm with fedora 27 and gameconqueror  and scannmem 
gameconqueror-0.17-1.fc27.x86_64
scanmem-libs-0.17-1.fc27.x86_64 

When i try to run in terminal with or without sudo it gave me 
`No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Impossible de se connecter : Connection refused

(GameConqueror.py:7037): Gtk-CRITICAL **: gtk_clipboard_get_for_display: assertion 'display != NULL' failed
/bin/gameconqueror : ligne 10 :  7037 Segmentation fault      (core dumped)$PKEXEC $DATADIR/GameConqueror.py "$@"
`

I try to uninstall and reinstall i don't work maybe its some wayland issue ?

**Comment by 12345ieee** [comment] 2017-12-31 14:44
I think you are affected by #263 .
This is an upstream issue in the wayland/pkexec interaction and we can only wait for it to be fixed.

In the meantime you can either use X or run GC as normal user (you might need to disable the Yama security module for it to work).

I also recommend filing a bug with your distro, or link it here, if you already did.

**Comment by 12345ieee** [comment] 2018-01-23 22:13
Closing as duplicate of #263 .

For google-nauts, @yodatak posted a workaround here: https://github.com/scanmem/scanmem/issues/263#issuecomment-354632024 .

**Closed by 12345ieee** 2018-01-23 22:13 UTC
