### ISSUE TITLE
Gui freezes at the end of differential search (Python 2 and 3)

### ISSUE THREAD

**Issue by GeoffMaciolek** [scanmem/scanmem#109] opened 2015-06-06 21:35 UTC
* **OS:**  Arch Linux 64 bit
* **scanmem/gameconqueror ver**: current from git as of 2015-06-06 (65c0bde)
* **Python2**: 2.7.9
* **Python3**: 3.4.3
* **/usr/bin/env python**: python3
* **Tested application**: TeleglitchDME v6.3 (Steam)

When performing searching operations, the GUI freezes on me.  So far this has only happened when I've been running with Python 3.  To switch, I actually edited `GameConqueror.py` to specify python2.

I can provide further details if requested, but I think it's the same issue reported on the [Arch Linux AUR page](https://aur.archlinux.org/packages/scanmem/).

**Comment by sriemer** [comment] 2015-06-06 22:34
Please run the `gameconqueror` command from console and provide the full Python 3 debug message. Also provide all search parameters you use. Data type and value for all searches.

**Comment by GeoffMaciolek** [comment] 2015-06-06 22:48
Error follows, my actions after:

<pre>Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "GameConqueror.py", line 892, in scan_thread_func
    self.update_scan_result()
  File "GameConqueror.py", line 915, in update_scan_result
    (a, o, rt, v, t) = list(map(str.strip, line.split(',')[:5]))
ValueError: need more than 4 values to unpack</pre>

I *think* this is the complete set of actions I took.  For what it's worth, it took a few searches for it to happen this time; I'm not 100% sure there's no issue on my machine in python2, but I haven't run into it yet.

* Search - number (40) - fine.
* Search - number (36) - fine.
* Edited
* Reset
* Search - number - ?
* Search - number - <
* Reset (whoops)
* Search - Number - 100
* Search - Number - <
* Search - Number - =
* Search - Number - <  (I hit enter, for what it's worth)

**Comment by GeoffMaciolek** [comment] 2015-06-06 22:52
Update - it does seem to only happen when doing great or less searches.  Will update this comment w/info on if it happens only on "number" or also on int/etc.

**Comment by GeoffMaciolek** [comment] 2015-06-06 23:11
Here - I dumped the value of the "line" variable as it led up to freezing, thought that might help!

<pre>Line:        b17f113,  2 +      1a21113,  heap, 0, [I32u ]
Line:        b17f114,  2 +      1a21114,  heap, 0, [I32 I16u ]
Line:        b17f14a,  2 +      1a2114a,  heap, -6537819283854131200, [I64s ]
Line:        b17f14e,  2 +      1a2114e,  heap, -1522204672, [I32s ]
Line:        b17f150,  2 +      1a21150,  heap, -23227, [I16s ]
Line:        b17f151,  2 +      1a21151,  heap, -91, [I8s ]
Line:        b17f1c2,  2 +      1a211c2,  heap, -6557241057247166464, [I64s ]
Line:        b17f1c3,  2 +      1a211c3,  heap, unknown

Exception in thread Thread-31:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "./GameConqueror.py", line 892, in scan_thread_func
    self.update_scan_result()
  File "./GameConqueror.py", line 916, in update_scan_result
    (a, o, rt, v, t) = list(map(str.strip, line.split(',')[:5]))
ValueError: need more than 4 values to unpack</pre>

**Comment by GeoffMaciolek** [comment] 2015-06-06 23:23
OK, here's the terrible debugging output I did to your beautiful code, and here's the output when it dies.

````python
            self.scanresult_liststore.clear()
            for line in lines:
                print ("Before formatting line: ", line)
                line = str(line.decode())
                line = line[line.find(']')+1:]
                print ("Line: ", line)
                (a, o, rt, v, t) = list(map(str.strip, line.split(',')[:5]))
                a = '%x'%(int(a,16),)
                o = '%x'%(int(o[5:],16),)
                t = t[1:-1]
                self.scanresult_liststore.append([a, v, t, True, o, rt])
            self.scanresult_tv.set_model(self.scanresult_liststore)
```` 


<pre>Before formatting line:  b'[ 0]      b57f1aa,  2 +      1e211aa,  heap, -91, [I8s ]\n'
Line:        b57f1aa,  2 +      1e211aa,  heap, -91, [I8s ]

Before formatting line:  b'[ 1]      b58c6c9,  2 +      1e2e6c9,  heap, -912489021085859239475151891374684329487341007717654698300410775952886302801560072929968299706053485956667771122677749433877649\n'
Line:        b58c6c9,  2 +      1e2e6c9,  heap, -912489021085859239475151891374684329487341007717654698300410775952886302801560072929968299706053485956667771122677749433877649

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "./GameConqueror.py", line 892, in scan_thread_func
    self.update_scan_result()
  File "./GameConqueror.py", line 917, in update_scan_result
    (a, o, rt, v, t) = list(map(str.strip, line.split(',')[:5]))
ValueError: need more than 4 values to unpack</pre>

**Comment by GeoffMaciolek** [comment] 2015-06-07 07:00
Issue persists with Python 2.7 apparently.  No idea why it wasn't for so long!

**Comment by sriemer** [comment] 2015-06-07 19:37
Thanks for your bug report! I can reproduce and therefore confirm the issue now for both Python 2 and 3. The problem is the following line:
````
Line:        b17f1c3,  2 +      1a211c3,  heap, unknown
````
The type is missing and therefore also the splitting doesn't work correctly. I'm looking for a solution for this.

The problem that issues in the GUI persist for so long is that neither Lu nor me use the GUI for production cheating. Searches using the GUI are slower than using scanmem directly and personally I don't like that a GUI requires root privileges - I even don't like that scanmem is doing so and this is why I have a special hack to make scanmem the parent of the game. The reason for this is the YAMA Linux security module (see: http://en.wikipedia.org/wiki/Ptrace).

So **we need voluntary GUI testers** testing the GUI with Python 2 and 3 all the time and reporting all bugs. But it seems that some users haven't understood yet how FOSS works. It means: Report a bug to upstream if a bug is bugging you that much that you want it to be fixed. With GitHub instead of Google code and Git instead of SVN we have a much better collaboration platform now and we try our best to be as active as possible. I had a big problem with inactivity in scanmem development. So I stepped in and asked if I could help. These are the reasons why we get much more pull requests and bug reports than before. I'm proud that we could close most of them by fixing bugs fast.

So are you willing to become a GUI tester for scanmem/GameConqueror?

**Comment by sriemer** [comment] 2015-06-07 20:20
The term "unknown" is only printed in `handlers.c` and only if the function `valtostr()` returns `false`.

`handlers.c` from function `handler__list()`:
````
 398                 if (valtostr(&val, v, buf_len) != true) {
 399                     strncpy(v, "unknown", buf_len);
 400                 }
````

`value.c` from function `valtostr()`:
````
 77     else {
 78         snprintf(str, n, "%#llx?, %s", get_slonglong(val), buf);
 79         return false;
 80     }
````
This is the only location where it returns `false`. And this output here is not visible. So `n` must be 0. But `n` is a function parameter of `valtostr()`.

The question now is why is `valtostr()` called with `n == 0`? And why doesn't the corner case handling print a type as well?

**Comment by sriemer** [comment] 2015-06-07 21:27
I've added printing to stderr of the values which get overwritten by "unknown". I get the following:
0xc10426e7bf?, []
0x6bfc1b40a0000?, []
0x6bfc1?, []
0xc0ef917a3f?, []

So we have 5 bytes, 7 bytes, 3 bytes and 5 bytes which are all no valid sizes for valid data types. Looks like these are the remaining bytes at the end of a region or something like that.

**Comment by sriemer** [comment] 2015-06-07 21:38
I've used git blame to check since when it is like that and the problem exists since 2010 it seems:

````
1f34f3e70e070 (coolwanglu              2010-01-09 12:27:15 +0000  77)     else {
1f34f3e70e070 (coolwanglu              2010-01-09 12:27:15 +0000  78)         snprintf(str, n, "%#llx?, %s", get_slonglong(val), buf);
1f34f3e70e070 (coolwanglu              2010-01-09 12:27:15 +0000  79)         return false;
^da4dc9e7d667 (taviso@sdf.lonestar.org 2007-12-16 23:03:54 +0000  80)     }

````

````
commit 1f34f3e70e070a1cddd8e2a5fb220752f93d777e
Author: coolwanglu <coolwanglu@0d3dcf9e-6d41-0410-9b3a-75061118c11e>
Date:   Sat Jan 9 12:27:15 2010 +0000

    implemented dataarray representation
````

**Comment by sriemer** [comment] 2015-06-07 22:38
I also see lines like this one where it crashes:
````
[455] 7f4d34a93f31, 29 +       9a9f31,  heap, -203491652152105397014976093528348262531447623339966256032020124268343046380274190882695717985193527532253679533774448847079140
````

**Comment by sriemer** [comment] 2015-06-07 22:59
@coolwanglu What did you do?

**Comment by sriemer** [comment] 2015-06-08 10:10
The error handling in and around `valtostr()` needs a full rework. I'm on it.

**Comment by coolwanglu** [comment] 2015-06-08 13:00
The clause in `valtostr` is for bytearrays, the length of the array is not stored, so there is no way to print a string representation of it. Yet the `snprintf` before `return false` indeed looks weird.
I remember that bytearray searching used to work...

**Comment by sriemer** [comment] 2015-06-08 15:05
This is about differential number search (<, >, =, ...). We get numbers with sizes not belonging to a valid data type or numbers which are too great to be valid. These results should be sorted out.

**Comment by GeoffMaciolek** [comment] 2015-06-08 15:07
I'm up for being a GUI tester, though I'm not 100% sure what my available time will be like.  But, I'm always excited about getting to contribute to FOSS projects, and have a sysadmin's eyes for stuff.  (Programmer? Not so much, though that's slowly re-developing; I lost all of my teenage skills).

One thing I wonder is - it looks like GameConqueror talks to scanmem - wouldn't it be possible to run scanmem itself as root, and have GameConqueror drop root privileges and talk to scanmem itself via some sort of ipc - DBUS, unix sockets, etc?

**Comment by sriemer** [comment] 2015-06-08 21:42
Please test and review PR #111. I'm very sure that I could fix it without introducing new problems. I did very thorough testing.

**Comment by GeoffMaciolek** [comment] 2015-06-09 01:15
PR #111 verified, so far no issues with the same behavior that caused me problems before.  **But** I'm not yet willing to write it off as "working" because it maaay be parsing a float "weirdly."  (This is something I'm far less certain of).

**Comment by sriemer** [comment] 2015-06-09 06:31
I've already seen big doubles. The GUI parses them and ignores the superfluous digits at the end. Parsing works. The GUI represents them in e-notation (e.g. -6.91070696903e-224). You could print the line coming from the scanmem `list` command with the value in the results list. I've already done that. It works.

**Comment by sriemer** [comment] 2015-06-21 06:50
The fix is merged. Thanks for the contribution!

**Closed** 2015-06-21 06:50 UTC
Labels: bug
