### ISSUE TITLE
Speedhack work for GameConqueror

### ISSUE THREAD

**Issue by GoogleCodeExporter** [scanmem/scanmem#65] opened 2015-03-14 06:57 UTC
```
Here is a source i've found searching on internet

http://code.google.com/p/xeat-engine/source/browse/#svn%2Ftrunk

i think devs can use it to make or try to redesing this to improve and insert 
into gameconqueror

... thanks


```

Original issue reported on code.google.com by `diegojp955` on 10 Jun 2013 at 7:16

**Comment by sriemer** [comment] 2015-03-21 16:26
That kind of speedhack lets the whole game run faster or slower for everything. I haven't seen a useful use case for this, yet. I like making only the stuff of the player run faster. E.g. in Warzone 2100 I take over control of all my Droid objects on the heap, reduce their weight and increase their base speed. Thanks to ugtrain only my Droids are fast - no matter how heavy.

It's visible here: https://www.youtube.com/watch?v=1GcppQNpdTc

So please provide use cases for a global speedhack.

**Comment by coolwanglu** [comment] 2015-03-23 02:50
Actually I used to this kind of hack a lot, sometimes the game becomes much easier when it is slower, where you need to response fast (platformers, sports, fighting etc), sometimes speed hack is part of the hacking, as the value might be changing fast. But the last case is not for scanmem, as it blocks the game when scanning.

**Comment by 12345ieee** [comment] 2016-01-09 15:52
List of use cases:
* Finding the right process when in doubt: try to freeze processes, when the game freezes you got the right one.
* Making the whole game go faster: idle games are prime examples of this, you want the whole game to speed up.
* Find a fast changing variable: it's not enough that scanmem blocks the game if I don't know what to search for before it starts.

**Comment by sriemer** [comment] 2016-01-09 17:24
For the first one and to avoid root privileges I run the game myself. Ugtrain is able to run scanmem as the parent of the game.

Patches and pull requests are welcome for this. We could also do a voting for this. The problem is that gettimeofday() needs to be hooked and API hooking is difficult if not starting the game ourselves.

Ugtrain is likely the better place as it runs the game and uses LD_PRELOAD (e.g. for malloc()) already.

**Comment by sriemer** [comment] 2016-03-30 07:19
Won't fix. Preloading or a different form of API hooking is required which conflicts with the need for root privileges.

**Closed by sriemer** 2016-03-30 07:19 UTC
Labels: enhancement
