### ISSUE TITLE
gui, Python 3: Certain float values cause a 'Bad Value' error

### ISSUE THREAD

**Issue by calculuswhiz** [scanmem/scanmem#140] opened 2015-11-01 14:16 UTC
I'm looking at the code for `misc.py`, and I can't figure out why searching for something like `1.0e9` or even `1.0` would cause a `Bad Value` error even for float values.

**Comment by sriemer** [comment] 2015-11-01 14:44
I can't reproduce that with Python 2.7. But with Python 3.4 I can. Thanks for reporting! Looks like we have another unicode coversion bug here.

**Comment by sriemer** [comment] 2015-11-01 14:55
[Line 96 in misc.py](https://github.com/scanmem/scanmem/blob/master/gui/misc.py#L96) has been changed for Python 3 as it doesn't support more than one value for `isinstance()`. That or the `eval()` function would be my guess. I'll analyze this further.
Thanks for reporting! Bug confirmed!

**Comment by sriemer** [comment] 2015-11-01 15:24
The type 'long' is the problem in `isinstance()`. Looks like Python 3 doesn't have it.

**Comment by sriemer** [comment] 2015-11-01 15:28
This works fine for Python 3:
````
diff --git a/gui/misc.py b/gui/misc.py
index 04f25a4f7b3f..b381e384cd7b 100644
--- a/gui/misc.py
+++ b/gui/misc.py
@@ -77,7 +77,7 @@ def check_scan_command (data_type, cmd, is_first_scan):
         cmd += str(num)
 
         if data_type.startswith('int'):
-            if not (isinstance(num, int) or isinstance(num, long)):
+            if not (isinstance(num, int)):
                 raise ValueError(_('%s is not an integer') % (num,))
             if data_type == 'int':
                 width = 64
@@ -93,7 +93,7 @@ def check_scan_command (data_type, cmd, is_first_scan):
 def eval_operand(s):
     try:
         v = eval(s)
-        if isinstance(v, int) or isinstance(v, long) or isinstance(v, float):
+        if isinstance(v, int) or isinstance(v, float):
             return v
     except:
         pass
````

**Comment by sriemer** [comment] 2015-11-01 15:55
The patch also works for Python 2.7. I've checked the value 8 billion for `int32` and `int64` - works as expected. Please confirm so that I can apply it!

**Comment by sriemer** [comment] 2015-11-01 16:22
I wrote a test tool to check finding the value 8 billion - works.

````
/* gcc -O0 -o test test.c */

#include <unistd.h>
#include <stdio.h>

unsigned long long magic_value = 8000000000ULL;

int main (void)
{
        unsigned long long i;

        while (1) {
                for (i = magic_value; i < magic_value + 10; i++) {
                        printf("magic_value: %llu, i: %llu\n", magic_value, i);
                        sleep(1);
                }
                i = magic_value;
        }
}
````

**Comment by sriemer** [comment] 2015-11-01 17:32
The patch is applied. So closing.
Man, and I thought that we would have finally caught all Python 3 bugs with v0.15.3, ...!

**Comment by calculuswhiz** [comment] 2015-11-02 00:52
Oops. Yeah, seems to work fine.

**Comment by sriemer** [comment] 2015-11-13 19:34
Removing `isinstance(v, long)` broke GameConqueror with Python 2 on i686. I've only tested this with x86_64 before. I'll create a fix.

**Comment by sriemer** [comment] 2015-11-13 20:09
The regression is fixed. So closing again.

**Closed by sriemer** 2015-11-13 20:09 UTC
Labels: bug
