### ISSUE TITLE
0.13-1: failed to attach to XXXX, No such process

### ISSUE THREAD

**Issue by VitaliyKulikov** [scanmem/scanmem#118] opened 2015-06-29 14:31 UTC
Infinitely popping up error message box with message `Backend error: failed to attach to XXXX, No such process` when you close XXXX process.

reproduce:
- run gameconqueror
- run `process` (can be run before)
- attach to `process`
- critical step: make 1st search and lock value added to cheat list (only this triggers the issue)
- close process
- infinite loop of re-opening msg box

reported issue on bugs.launchpad.net: https://bugs.launchpad.net/ubuntu/+source/scanmem/+bug/1468443

**Comment by sriemer** [comment] 2015-06-29 23:47
Version 0.13-1 is quite old already. I can't reproduce this with latest v0.15.2. There is no message box displayed in that case. It is printed on the console when running `gameconqueror` from command line but that's it. Distributions should all update to version 0.15.2 as we have some major performance improvement and GUI fixes in there. I don't think that it makes sense to create bugfix patches to fix this old version.

**Comment by sriemer** [comment] 2015-06-30 08:46
If I would be the Debian/Ubuntu package maintainer, then I would update the version in everything starting from 12.04 Precise.

**Comment by coolwanglu** [comment] 2015-06-30 08:47
Oh I didn't notice the version number in the original bug report. In this case we should close it.

**Closed by coolwanglu** 2015-06-30 08:47 UTC

**Comment by sriemer** [comment] 2015-06-30 08:49
Will you update the Debian/Ubuntu package?

**Comment by coolwanglu** [comment] 2015-06-30 08:51
No, I'm not the maintainer.

**Comment by sriemer** [comment] 2015-06-30 08:55
That means then that @kartikm should do. Btw: I've already talked to the Arch and Fedora maintainers. They'll update.

**Comment by coolwanglu** [comment] 2015-06-30 08:56
OK Thanks.

**Comment by VitaliyKulikov** [comment] 2015-06-30 22:49
thanks for clarification and quick response )
