### ISSUE TITLE
Pointers pls

### ISSUE THREAD

**Issue by Drui7** [scanmem/scanmem#315] opened 2018-04-22 23:05 UTC
I want to be able to create a list of pointers to values. or pointers to pointers to values. or even more levels of nesting. so that you can once find the value and use it at each start.

**Comment by 12345ieee** [comment] 2018-04-23 19:33
This is a duplicate of #301 , which has an in-depth technical discussion.

scanmem/GC can't do it, you need something with the capabilities of a debugger.
So `gdb`, `ugtrain` and possibly `PINCE`.

**Closed by 12345ieee** 2018-04-23 19:33 UTC
