### ISSUE TITLE
Google Chrome exits when changing a value

### ISSUE THREAD

**Issue by tigefa4u** [scanmem/scanmem#126] opened 2015-08-11 05:55 UTC
crash after change value in flash game online.

**Comment by sriemer** [comment] 2015-08-11 06:31
Don't you think that you should provide more details?
What crashed? The game or the browser or scanmem or GameConqueror?
Which version (or commit) of scanmem do you use?
Is it reproducible?
Is it reproducible with scanmem from latest Git HEAD?
How to reproduce it?
Please write down which browser + version, game, URL and which steps are required to reproduce.
Do you have a coredump and the scanmem binary compiled with debugging symbols from latest Git HEAD?
Have you checked `dmesg` for segfault messages?

Example:
````
[  515.356535] segfault[6116]: segfault at 0 ip 0000000000400400 sp 00007fff913be0a8 error 6 in segfault[400000+1000]
````

**Comment by sriemer** [comment] 2015-08-11 08:23
Let me guess: You're using the Google Chrome browser and wonder why it exits when writing a value?

Chrome uses a security method known as **anti-ptrace**.

Anti-ptrace:
Ptrace() is detected with ptrace(PTRACE_TRACEME, ...).

Anti-Anti-ptrace:
So wrapping of libc ptrace() in a lib with LD_PRELOAD helps.

Anti-Anti-Anti-ptrace aka Anti-LD_PRELOAD:
Now, the idea is to detect the LD_PRELOAD env var with getenv("LD_PRELOAD");.

Anti-Anti-LD_PRELOAD:
In the lib constructor unsetenv("LD_PRELOAD"); can be used as the lib is already preloaded before main() is called.

Lib constructor example:
void __attribute ((constructor)) lib_init (void);

References:
man ptrace
man getenv
man unsetenv
man ld.so

Unfortunately, scanmem and GameConqueror don't use the best approach (requiring root privileges) and don't run their victim process themselves. This is why these can't use LD_PRELOAD.

Have a look at the Universal Elite Game Trainer [ugtrain](https://github.com/ugtrain/ugtrain/) if you want to see LD_PRELOAD in action against games.

**Comment by tigefa4u** [comment] 2015-08-11 08:59
yes, i use old version scanmem version 0.13 GameConqueror 0.13 and Google Chrome 44.0.2403.130
how to i can get PPA for latest version?

**Comment by sriemer** [comment] 2015-08-11 09:59
One of us maintainers (@coolwanglu or me) or the Debian package maintainer (@kartikm) has to create the Debian package and this has to be put into a PPA. For me it is also annoying that Ubuntu and Debian still use 4 years old 0.13 (see #119). Or you just compile from source.

But latest scanmem is also affected. **Google Chrome is smart.**

I had a look at this commit which introduced the anti-ptrace:
https://chromium.googlesource.com/chromium/src/+/866d1af17255d751c1f2feb828bba20bd25ffaae%5E!/

They block the whole syscall via the seccomp filters, I just found out. So prctl(PR_SET_SECCOMP, ...) has to be hooked with LD_PRELOAD which is impossible to do with scanmem/GameConqueror as I mentioned.

But for ugtrain this would be feasible. It runs scanmem as the parent of the game/browser. This is why using scanmem together with ugtrain doesn't require root privileges and allows preloading hooking libraries. ;-) There is the **Yama security module** which limits the ptrace() system call.

References:
man prctl
https://www.kernel.org/doc/Documentation/prctl/seccomp_filter.txt
https://www.kernel.org/doc/Documentation/security/Yama.txt

**Comment by tigefa4u** [comment] 2015-08-11 14:12
found one
https://launchpad.net/~coolwanglu/+archive/ubuntu/scanmem
but my Ubuntu not listed
> Distributor ID:	Ubuntu
> Description:	Ubuntu 14.04.3 LTS
> Release:	14.04
> Codename:	trusty

**Comment by sriemer** [comment] 2015-08-12 19:57
Just checked with Firefox 39.0. There it is no problem attaching to the "plugin-container" process and to modify found values in Flash games.

**Comment by sriemer** [comment] 2015-08-12 21:03
I've also checked latest Google Chrome Version 44.0.2403.155 (64-bit) from the .deb file. When attaching directly to the Flash process, then changing values works fine with scanmem without using any GameConqueror.

````
$ ps aux | grep chrome | grep flash
user 19956  4.3  0.4 751644 71564 ?        Sl   22:52   0:16 /opt/google/chrome/chrome --type=ppapi --channel=19736.7.891554328 --ppapi-flash-args --lang=en-US --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
$ sudo scanmem -p 19956
````

**Comment by sriemer** [comment] 2015-08-12 21:20
IMHO this issue can be closed as I can't reproduce it with scanmem from latest git HEAD and the mentioned Google Chrome version. It's strange that it doesn't block the ptrace() syscall any more.
Please provide more info if you want this to be debugged in more detail!

**Closed** 2015-08-18 05:25 UTC
Labels: help wanted
