### ISSUE TITLE
Paths with spaces get cut off in lregions

### ISSUE THREAD

**Issue by no-boot-device** [scanmem/scanmem#166] opened 2016-06-06 20:52 UTC
Any path that has a space in it in /proc/[pid]/maps will only show up to the space in lregions, after which it will be cut off.
This is pretty annoying when the application you're messing with loads stuff from a directory with a space in it.

**Comment by sriemer** [comment] 2016-06-07 07:35
I get "unassociated" if moving the executable to a directory with a space.

**Comment by sriemer** [comment] 2016-06-07 07:43
The problem is the [`sscanf()` in maps.c](https://github.com/scanmem/scanmem/blob/f81645b88d699bcbba0886de25d19d7880e3246e/maps.c#L106).

**Comment by sriemer** [comment] 2016-06-07 07:58
What about replacing `%s` with `%[^\n()]` meaning match everything except '\n' '(' and ')'?
This way the "(deleted)" is ignored and spaces are possible.
Reference: `man sscanf`

**Comment by sriemer** [comment] 2016-06-07 08:20
@coolwanglu, @anthraxx, @ignatenkobrain, @12345ieee, @3vil, @Funmungus, @calculuswhiz, any objections?

TODO:
* test on Raspberry Pi for ARM
* check with Coverity Scan
* let @Funmungus test on Android

**Comment by 12345ieee** [comment] 2016-06-07 08:24
Trying hard to break your solution, what stops me from loading from
`"/home/IhateYouAll/(deleted) (deleted)"` (a valid filename)
and completely breaking your solution?

It would be better to match everything that can be in a filename (everything but `NUL`, `/` and special dirs) up to '\n' and then checking if there is a `(deleted)` tacked at the end.

**Comment by sriemer** [comment] 2016-06-07 08:33
Basically I don't care if there is a (deleted) in it or not. Might be only confusing for some users. I'm also fine with `%[^\n]` matching everything which is not a newline. It also stops at '\0'.

**Comment by 12345ieee** [comment] 2016-06-07 08:37
Thinking about it a little better, files that end in `(deleted)` are completely indistinguishable from deleted locations, unless the `maps` file does something fancy about them (I cannot try right now), so you can't really hope to cut away the `(deleted)` and cover both cases.

`%[^\n]` is simple and never cuts the filename, I am all for it.

**Comment by sriemer** [comment] 2016-06-07 08:46
Thanks, so `%[^\n]` is preferred for now. This is also my vote now.

**Comment by 12345ieee** [comment] 2016-06-07 08:54
I actually tried what happens, I called an executable `"thing (deleted)"` and deleted it mid-execution.

Before deletion:

    NUMBERS PATH/thing (deleted)

After deletion:

    NUMBERS PATH/thing (deleted) (deleted)

So there's no way you can distinguish a file that really ends in `(deleted)` from a deleted file.
Pretty sure no sane person will ever need to distinguish between the two.

**Comment by sriemer** [comment] 2016-06-07 19:11
Coverity Scan doesn't complain, also works on Raspberry Pi / ARM, fix committed. So closing.

**Closed by sriemer** 2016-06-07 19:11 UTC
Labels: bug

**Comment by sriemer** [comment] 2016-06-07 19:37
Also applied to [ugtrain](https://github.com/ugtrain/ugtrain/commit/fbf155dfa9bfa1e2468b66ebb2d0a9c0bcf3c5a2).

**Comment by Funmungus** [comment] 2016-06-27 06:54
I have seen this in Android, and I will test for it.  I will also look in Ubuntu Touch to see if the same thing happens and is fixed.
