### ISSUE TITLE
Scan time of non-fixed-width types

### ISSUE THREAD

**Issue by 12345ieee** [scanmem/scanmem#226] opened 2016-10-11 16:14 UTC
Follows a very simple benchmark (against master):

```
andreas@trelitri:~/Progetti/scanmem$ time echo -e 'option scan_data_type int8\n0x64' | ./scanmem -p`pidof geany` 2>/dev/null
0> option scan_data_type int8
0> 100
136661> 
real    0m0,868s
user    0m0,788s
sys 0m0,076s

andreas@trelitri:~/Progetti/scanmem$ time echo -e 'option scan_data_type string\n" d' | ./scanmem -p`pidof geany` 2>/dev/null
0> option scan_data_type string
0> " d
136661> 
real    0m1,715s
user    0m1,648s
sys 0m0,060s

andreas@trelitri:~/Progetti/scanmem$ time echo -e 'option scan_data_type bytearray\n64' | ./scanmem -p`pidof geany` 2>/dev/null
0> option scan_data_type bytearray
0> 64
136661> 
real    0m1,752s
user    0m1,692s
sys 0m0,052s
```

in which we can see that looking for the **same exact 8 bits** with `int8` is twice as fast than doing it by non-fixed-width types. Same result for an int16 and a 2 char string.

Can we do something about this?

**Comment by sriemer** [comment] 2016-10-12 16:23
Sure. First of all create a test tool which creates enough data to keep scanmem busy for at least 10s for reliable benchmark results and reproducible data so that we have the same test case for this.

E.g. I test the scanmem integer search performance with a small C-tool which uses a 500 MiB calloc(). Source: https://github.com/sriemer/spars-coding/tree/master/memfake

Then you can do Valgrind callgrind performance profiling to locate the bottlenecks. But it runs 20 times slower. So do that on 20 times smaller data. #107 shows how that works.

That valgrind stuff is also not precise. It doesn't actually measure the time spent in syscalls. So it can't detect that ptrace() is quite slow. Valgrind does CPU time estimations. So it can only find CPU intensive calculations. A different profiler like OProfile might be better.

**Comment by sriemer** [comment] 2016-10-12 17:55
![string_search_callgrind](https://cloud.githubusercontent.com/assets/1803210/19321297/c7135f7a-90b4-11e6-8f7b-ad90f42d2821.png)

The function `scan_routine_STRING_EQUALTO()` has just much more complex assembly code. So look at `scanroutines.c` for performance improvement.

I'd like to inline all scan routines as they cost a function call for every byte or use fancy new GCC features to do live code-replacement like the Linux kernel does.
You can see in the picture that I've searched for a string in 500 MiB of memory.

**Comment by sriemer** [comment] 2016-10-12 18:30
This was much worse before we've started with performance optimization.
You can see that a huge part of the time is spent in `searchregions()` where it has to be spent. It has been achieved by massive inlining.

**Comment by 12345ieee** [comment] 2016-10-12 22:25
*First time I look into `ptrace.c` in detail*
Are we seriously using a function pointer to the checking function in the hot scanning path?

Now I get what you mean by inlining, I thought they were regular functions and the compiler preferred somehow to leave the function call.

We are also (AFAI understand) using the simple bruteforce algorithm to solve the "needle-in-the-haystack" problem, but as our needle is usually very small, that's probably the best and most reasonable solution.

I can also see string/bytearray comparators are like 5x longer in C than numeric ones, and they seem to compare 8byte-by-8byte (and then 1-by-1) instead of using a `memcmp()`, but that's not relevant for 1 byte strings.

I'll have a more through look later, after feeding it to `cpp` to have the macros expanded.
If you have info on whatever algorithm/rationale/whatever was used, I'll be happy to hear, or I'll take ages to figure it out.

**Comment by sriemer** [comment] 2016-10-13 08:54
Yes, there is a function pointer and functions from function pointers can't be inlined. Also functions which are located in a different `.c` file can't be inlined. So I force inlining by moving them to header files at static inline functions as recommended by the Linux kernel development guidelines. Also gcc is lazy at inlining.

There is very naive text search implemented to keep the function pointer interface the same for all search functions. The function also reads the next byte internally. There is improvement potential I'm sure.

**Comment by 12345ieee** [comment] 2016-10-23 15:35
I tested with `memfake` (aka "every byte matches") and to my huge surprise, int8 is as fast as the other 2.

When I sprinkled memfake's memory with some payload bytes (~100 in my case) and looked for them, I got back the 2x difference.

No idea what is happening here.

**Comment by 12345ieee** [comment] 2016-10-23 17:41
Ok, hardcoding the length (instead of retrieving it from the uservalue) makes the times equal.

Apart a "small strings optimization" for strings/bytearrays of 1,2,4 bytes, I don't see a way to work around this.

Opportunities to improve other things sure are plenty, see #227 for an example.

**Comment by 12345ieee** [comment] 2017-07-03 16:33
So, I had another look at the code.

Inlining the scanning function by force, by copying it and compiling it in clearly gives a good speed boost, but I've found other ways to improve performance.

If we consider a compound `scan_function`, like `int`, it currently calls the other 4 simple types, which is a monumental waste. It's possible to convince the compiler to emit both a callable version, to be called from `searchregions/checkmatches` by pointer and an inlined version that can be put into the compound functions, by declaring them `extern inline`. See 12345ieee@a5ed5e5 .

Some data (`scan_data_type int; 0` on ~30 MB of mostly 0s on an i7-5500U):

| Code | Time | Time with LTO (see below)
| :- | :- | :- 
| Current (Double call) | 3.8s | 3.8s
| Partially inlined ( 12345ieee@a5ed5e5 ) | 3.3s | 3.0s
| Completely inlined | 3.0s | 4.8s

So we gain already 60% of what full inlining can do with a trivial change, when using `scan_data_type number` it's even more noticeable). Performance of the single type functions is unaffected (full inlining would gain a ~10% here as well).

@sriemer , I'd like this simple change in 12345ieee@a5ed5e5 merged ASAP, I can make a single commit PR if needed.

I have also tried some compiler magic, by adding `-flto` to `Makefile.am`, but results are so inconclusive that I'd never want to mess with it.

**Comment by sriemer** [comment] 2017-07-10 07:55
Looks good but this breaks compilation on openSUSE. Compiler option `-std=gnu99` is required for this.

**Comment by 12345ieee** [comment] 2017-07-10 08:12
That's a good point, this behaviour changed between C89 and C99.
We decided `scanmem` was C99, I applied the C99 version (I compile with C11 by default).

I'll add a commit before this one on my branch, moving to C99.

**Comment by 12345ieee** [comment] 2017-07-10 08:19
Here it is: 12345ieee@1b9fd8d and 12345ieee@c144290

**Comment by sriemer** [comment] 2017-07-11 07:30
This is merged now. Thanks! Checked with `objdump -S` and my `memfake` tool. Searching for "10" in 500 MiB of zeroed memory drops from 6.9s to 4s. That's 42% less scan time. Looks like your measurement was too imprecise as I get much better results.

**Comment by sriemer** [comment] 2017-07-11 07:34
I have to change my tool `memfake` to allocate 1 GiB and more now as scanmem became too fast. 😉

**Comment by 12345ieee** [comment] 2017-07-11 08:11
@sriemer , I was searching for '0' (nearly everything matches), so I was also exercising the path that stores matched values.

If you don't, you clearly get better relative performance, I get a -40% as well searching '10', great agreement.

I have ~15 more `scanmem`-related commits that I'd like to merge (some other time improvements as well), do I make a PR?

**Comment by 12345ieee** [comment] 2017-07-14 10:14
So, I have finally studied this whole thing in-depth.

What generally slows **string** routines down (bytearray is even worse) is:
* accessing the `user_value->length`, then using it to make decisions.
* testing entry conditions for several loops

Note that `memcmp` DOES NOT help, at least on my machine/compiler.

So, I solved the issue in 3 parts (times are for a 'nearly nothing matches', which is the usual case) :

* len is 1,2,4,8: cast to uintNN and compare, this is as fast as integer comparisons (time -60%)
* len is 3,5,6,7: remove the uint64 possible compare loop and hardcode the loop length in each, nearly as fast as the above (time -55%)
* len is >8: compare the first 8 bytes immediately, then if needed access length and start doing loops, (time -40%)

The scan selection routine is a bit more complicated, because the length needs to passed down the chain, but I don't think this is a problem.

I attach a patch series, as my branch is too much of a mess. They do not apply cleanly on this master, but they should be enough for you to understand the changes.
A working version is my 12345ieee/scanmem/master , as usual, but it's currently not very pretty
[0001-Implement-initial-version-of-fast-scan-for-small-str.patch.txt](https://github.com/scanmem/scanmem/files/1148064/0001-Implement-initial-version-of-fast-scan-for-small-str.patch.txt)
[0002-v2-ssstr.patch.txt](https://github.com/scanmem/scanmem/files/1148066/0002-v2-ssstr.patch.txt)
[0003-smallstr-v3.patch.txt](https://github.com/scanmem/scanmem/files/1148065/0003-smallstr-v3.patch.txt)

Extending this to a fixed bytearray is not too difficult, but I'd like to know if the present approach is problematic.

**Comment by sriemer** [comment] 2017-07-17 06:41
The approach sounds good. I did something similar for `memset()` already. Unknown size is always bad for performance.

**Comment by sriemer** [comment] 2017-07-17 06:44
Btw.: You're an owner now. So you can commit things on your own now so that it doesn't all depend on me any more. With Lu Wang it was never agreed that I would maintain scanmem/GC alone.

**Comment by 12345ieee** [comment] 2017-07-17 12:02
Thank you, @sriemer , I'll clean this out and then merge a bunch of gui stuff we've left behind since last year.

As for this series, I think I'm going to make a "fixed bytearray" type that can share everything with string but the printing, so I can automatically port the improvements.

**Closed** 2017-08-24 08:25 UTC
Labels: enhancement, question
